// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.13.0
//  VPP:              26.06-rc0~373-ge425dad65
// source: plugins/tlsctrl_vpn.api.json

// Package tlsctrl_vpn contains generated bindings for API file tlsctrl_vpn.api.
//
// Contents:
// - 19 messages
package tlsctrl_vpn

import (
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "tlsctrl_vpn"
	APIVersion = "0.1.7"
	VersionCrc = 0x73a6572d
)

// TlsctrlVPNConnectConfigGet defines message 'tlsctrl_vpn_connect_config_get'.
type TlsctrlVPNConnectConfigGet struct {
	Username string `binapi:"string[64],name=username" json:"username,omitempty"`
	Profile  string `binapi:"string[64],name=profile" json:"profile,omitempty"`
	ClientIP string `binapi:"string[64],name=client_ip" json:"client_ip,omitempty"`
}

func (m *TlsctrlVPNConnectConfigGet) Reset()               { *m = TlsctrlVPNConnectConfigGet{} }
func (*TlsctrlVPNConnectConfigGet) GetMessageName() string { return "tlsctrl_vpn_connect_config_get" }
func (*TlsctrlVPNConnectConfigGet) GetCrcString() string   { return "b8407dd0" }
func (*TlsctrlVPNConnectConfigGet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlVPNConnectConfigGet) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 64 // m.Username
	size += 64 // m.Profile
	size += 64 // m.ClientIP
	return size
}
func (m *TlsctrlVPNConnectConfigGet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Username, 64)
	buf.EncodeString(m.Profile, 64)
	buf.EncodeString(m.ClientIP, 64)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNConnectConfigGet) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Username = buf.DecodeString(64)
	m.Profile = buf.DecodeString(64)
	m.ClientIP = buf.DecodeString(64)
	return nil
}

// TlsctrlVPNConnectConfigGetReply defines message 'tlsctrl_vpn_connect_config_get_reply'.
type TlsctrlVPNConnectConfigGetReply struct {
	Retval        int32  `binapi:"i32,name=retval" json:"retval,omitempty"`
	TunnelID      uint32 `binapi:"u32,name=tunnel_id" json:"tunnel_id,omitempty"`
	AssignedIP    string `binapi:"string[64],name=assigned_ip" json:"assigned_ip,omitempty"`
	Gateway       string `binapi:"string[64],name=gateway" json:"gateway,omitempty"`
	DNSServers    string `binapi:"string[256],name=dns_servers" json:"dns_servers,omitempty"`
	IncludeRoutes string `binapi:"string[512],name=include_routes" json:"include_routes,omitempty"`
	ExcludeRoutes string `binapi:"string[512],name=exclude_routes" json:"exclude_routes,omitempty"`
	FullTunnel    bool   `binapi:"bool,name=full_tunnel" json:"full_tunnel,omitempty"`
	Mtu           uint16 `binapi:"u16,name=mtu" json:"mtu,omitempty"`
	MssClamp      uint16 `binapi:"u16,name=mss_clamp" json:"mss_clamp,omitempty"`
	LeaseSeconds  uint32 `binapi:"u32,name=lease_seconds" json:"lease_seconds,omitempty"`
}

func (m *TlsctrlVPNConnectConfigGetReply) Reset() { *m = TlsctrlVPNConnectConfigGetReply{} }
func (*TlsctrlVPNConnectConfigGetReply) GetMessageName() string {
	return "tlsctrl_vpn_connect_config_get_reply"
}
func (*TlsctrlVPNConnectConfigGetReply) GetCrcString() string { return "371038ba" }
func (*TlsctrlVPNConnectConfigGetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlVPNConnectConfigGetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4   // m.Retval
	size += 4   // m.TunnelID
	size += 64  // m.AssignedIP
	size += 64  // m.Gateway
	size += 256 // m.DNSServers
	size += 512 // m.IncludeRoutes
	size += 512 // m.ExcludeRoutes
	size += 1   // m.FullTunnel
	size += 2   // m.Mtu
	size += 2   // m.MssClamp
	size += 4   // m.LeaseSeconds
	return size
}
func (m *TlsctrlVPNConnectConfigGetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint32(m.TunnelID)
	buf.EncodeString(m.AssignedIP, 64)
	buf.EncodeString(m.Gateway, 64)
	buf.EncodeString(m.DNSServers, 256)
	buf.EncodeString(m.IncludeRoutes, 512)
	buf.EncodeString(m.ExcludeRoutes, 512)
	buf.EncodeBool(m.FullTunnel)
	buf.EncodeUint16(m.Mtu)
	buf.EncodeUint16(m.MssClamp)
	buf.EncodeUint32(m.LeaseSeconds)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNConnectConfigGetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.TunnelID = buf.DecodeUint32()
	m.AssignedIP = buf.DecodeString(64)
	m.Gateway = buf.DecodeString(64)
	m.DNSServers = buf.DecodeString(256)
	m.IncludeRoutes = buf.DecodeString(512)
	m.ExcludeRoutes = buf.DecodeString(512)
	m.FullTunnel = buf.DecodeBool()
	m.Mtu = buf.DecodeUint16()
	m.MssClamp = buf.DecodeUint16()
	m.LeaseSeconds = buf.DecodeUint32()
	return nil
}

// TlsctrlVPNPoolDetails defines message 'tlsctrl_vpn_pool_details'.
type TlsctrlVPNPoolDetails struct {
	Name         string `binapi:"string[64],name=name" json:"name,omitempty"`
	Subnet       string `binapi:"string[64],name=subnet" json:"subnet,omitempty"`
	Gateway      string `binapi:"string[64],name=gateway" json:"gateway,omitempty"`
	LeaseSeconds uint32 `binapi:"u32,name=lease_seconds" json:"lease_seconds,omitempty"`
	ActiveLeases uint32 `binapi:"u32,name=active_leases" json:"active_leases,omitempty"`
	LeaseCursor  uint32 `binapi:"u32,name=lease_cursor" json:"lease_cursor,omitempty"`
}

func (m *TlsctrlVPNPoolDetails) Reset()               { *m = TlsctrlVPNPoolDetails{} }
func (*TlsctrlVPNPoolDetails) GetMessageName() string { return "tlsctrl_vpn_pool_details" }
func (*TlsctrlVPNPoolDetails) GetCrcString() string   { return "5d6d14af" }
func (*TlsctrlVPNPoolDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlVPNPoolDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 64 // m.Name
	size += 64 // m.Subnet
	size += 64 // m.Gateway
	size += 4  // m.LeaseSeconds
	size += 4  // m.ActiveLeases
	size += 4  // m.LeaseCursor
	return size
}
func (m *TlsctrlVPNPoolDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Name, 64)
	buf.EncodeString(m.Subnet, 64)
	buf.EncodeString(m.Gateway, 64)
	buf.EncodeUint32(m.LeaseSeconds)
	buf.EncodeUint32(m.ActiveLeases)
	buf.EncodeUint32(m.LeaseCursor)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNPoolDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Name = buf.DecodeString(64)
	m.Subnet = buf.DecodeString(64)
	m.Gateway = buf.DecodeString(64)
	m.LeaseSeconds = buf.DecodeUint32()
	m.ActiveLeases = buf.DecodeUint32()
	m.LeaseCursor = buf.DecodeUint32()
	return nil
}

// TlsctrlVPNPoolDump defines message 'tlsctrl_vpn_pool_dump'.
type TlsctrlVPNPoolDump struct{}

func (m *TlsctrlVPNPoolDump) Reset()               { *m = TlsctrlVPNPoolDump{} }
func (*TlsctrlVPNPoolDump) GetMessageName() string { return "tlsctrl_vpn_pool_dump" }
func (*TlsctrlVPNPoolDump) GetCrcString() string   { return "51077d14" }
func (*TlsctrlVPNPoolDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlVPNPoolDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *TlsctrlVPNPoolDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNPoolDump) Unmarshal(b []byte) error {
	return nil
}

// TlsctrlVPNPoolSet defines message 'tlsctrl_vpn_pool_set'.
type TlsctrlVPNPoolSet struct {
	Name         string `binapi:"string[64],name=name" json:"name,omitempty"`
	Subnet       string `binapi:"string[64],name=subnet" json:"subnet,omitempty"`
	Gateway      string `binapi:"string[64],name=gateway" json:"gateway,omitempty"`
	LeaseSeconds uint32 `binapi:"u32,name=lease_seconds" json:"lease_seconds,omitempty"`
}

func (m *TlsctrlVPNPoolSet) Reset()               { *m = TlsctrlVPNPoolSet{} }
func (*TlsctrlVPNPoolSet) GetMessageName() string { return "tlsctrl_vpn_pool_set" }
func (*TlsctrlVPNPoolSet) GetCrcString() string   { return "da3bc5ef" }
func (*TlsctrlVPNPoolSet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlVPNPoolSet) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 64 // m.Name
	size += 64 // m.Subnet
	size += 64 // m.Gateway
	size += 4  // m.LeaseSeconds
	return size
}
func (m *TlsctrlVPNPoolSet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Name, 64)
	buf.EncodeString(m.Subnet, 64)
	buf.EncodeString(m.Gateway, 64)
	buf.EncodeUint32(m.LeaseSeconds)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNPoolSet) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Name = buf.DecodeString(64)
	m.Subnet = buf.DecodeString(64)
	m.Gateway = buf.DecodeString(64)
	m.LeaseSeconds = buf.DecodeUint32()
	return nil
}

// TlsctrlVPNPoolSetReply defines message 'tlsctrl_vpn_pool_set_reply'.
type TlsctrlVPNPoolSetReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlVPNPoolSetReply) Reset()               { *m = TlsctrlVPNPoolSetReply{} }
func (*TlsctrlVPNPoolSetReply) GetMessageName() string { return "tlsctrl_vpn_pool_set_reply" }
func (*TlsctrlVPNPoolSetReply) GetCrcString() string   { return "e8d4e804" }
func (*TlsctrlVPNPoolSetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlVPNPoolSetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlVPNPoolSetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNPoolSetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// TlsctrlVPNPoolSetReplyReply defines message 'tlsctrl_vpn_pool_set_reply_reply'.
type TlsctrlVPNPoolSetReplyReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlVPNPoolSetReplyReply) Reset() { *m = TlsctrlVPNPoolSetReplyReply{} }
func (*TlsctrlVPNPoolSetReplyReply) GetMessageName() string {
	return "tlsctrl_vpn_pool_set_reply_reply"
}
func (*TlsctrlVPNPoolSetReplyReply) GetCrcString() string { return "e8d4e804" }
func (*TlsctrlVPNPoolSetReplyReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlVPNPoolSetReplyReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlVPNPoolSetReplyReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNPoolSetReplyReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// TlsctrlVPNProfileDetails defines message 'tlsctrl_vpn_profile_details'.
type TlsctrlVPNProfileDetails struct {
	Name          string `binapi:"string[64],name=name" json:"name,omitempty"`
	Pool          string `binapi:"string[64],name=pool" json:"pool,omitempty"`
	FullTunnel    bool   `binapi:"bool,name=full_tunnel" json:"full_tunnel,omitempty"`
	Mtu           uint16 `binapi:"u16,name=mtu" json:"mtu,omitempty"`
	MssClamp      uint16 `binapi:"u16,name=mss_clamp" json:"mss_clamp,omitempty"`
	DNSServers    string `binapi:"string[256],name=dns_servers" json:"dns_servers,omitempty"`
	IncludeRoutes string `binapi:"string[512],name=include_routes" json:"include_routes,omitempty"`
	ExcludeRoutes string `binapi:"string[512],name=exclude_routes" json:"exclude_routes,omitempty"`
}

func (m *TlsctrlVPNProfileDetails) Reset()               { *m = TlsctrlVPNProfileDetails{} }
func (*TlsctrlVPNProfileDetails) GetMessageName() string { return "tlsctrl_vpn_profile_details" }
func (*TlsctrlVPNProfileDetails) GetCrcString() string   { return "fb19d1c0" }
func (*TlsctrlVPNProfileDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlVPNProfileDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 64  // m.Name
	size += 64  // m.Pool
	size += 1   // m.FullTunnel
	size += 2   // m.Mtu
	size += 2   // m.MssClamp
	size += 256 // m.DNSServers
	size += 512 // m.IncludeRoutes
	size += 512 // m.ExcludeRoutes
	return size
}
func (m *TlsctrlVPNProfileDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Name, 64)
	buf.EncodeString(m.Pool, 64)
	buf.EncodeBool(m.FullTunnel)
	buf.EncodeUint16(m.Mtu)
	buf.EncodeUint16(m.MssClamp)
	buf.EncodeString(m.DNSServers, 256)
	buf.EncodeString(m.IncludeRoutes, 512)
	buf.EncodeString(m.ExcludeRoutes, 512)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNProfileDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Name = buf.DecodeString(64)
	m.Pool = buf.DecodeString(64)
	m.FullTunnel = buf.DecodeBool()
	m.Mtu = buf.DecodeUint16()
	m.MssClamp = buf.DecodeUint16()
	m.DNSServers = buf.DecodeString(256)
	m.IncludeRoutes = buf.DecodeString(512)
	m.ExcludeRoutes = buf.DecodeString(512)
	return nil
}

// TlsctrlVPNProfileDump defines message 'tlsctrl_vpn_profile_dump'.
type TlsctrlVPNProfileDump struct{}

func (m *TlsctrlVPNProfileDump) Reset()               { *m = TlsctrlVPNProfileDump{} }
func (*TlsctrlVPNProfileDump) GetMessageName() string { return "tlsctrl_vpn_profile_dump" }
func (*TlsctrlVPNProfileDump) GetCrcString() string   { return "51077d14" }
func (*TlsctrlVPNProfileDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlVPNProfileDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *TlsctrlVPNProfileDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNProfileDump) Unmarshal(b []byte) error {
	return nil
}

// TlsctrlVPNProfileSet defines message 'tlsctrl_vpn_profile_set'.
type TlsctrlVPNProfileSet struct {
	Name          string `binapi:"string[64],name=name" json:"name,omitempty"`
	Pool          string `binapi:"string[64],name=pool" json:"pool,omitempty"`
	FullTunnel    bool   `binapi:"bool,name=full_tunnel" json:"full_tunnel,omitempty"`
	Mtu           uint16 `binapi:"u16,name=mtu" json:"mtu,omitempty"`
	MssClamp      uint16 `binapi:"u16,name=mss_clamp" json:"mss_clamp,omitempty"`
	DNSServers    string `binapi:"string[256],name=dns_servers" json:"dns_servers,omitempty"`
	IncludeRoutes string `binapi:"string[512],name=include_routes" json:"include_routes,omitempty"`
	ExcludeRoutes string `binapi:"string[512],name=exclude_routes" json:"exclude_routes,omitempty"`
}

func (m *TlsctrlVPNProfileSet) Reset()               { *m = TlsctrlVPNProfileSet{} }
func (*TlsctrlVPNProfileSet) GetMessageName() string { return "tlsctrl_vpn_profile_set" }
func (*TlsctrlVPNProfileSet) GetCrcString() string   { return "27d2fd24" }
func (*TlsctrlVPNProfileSet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlVPNProfileSet) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 64  // m.Name
	size += 64  // m.Pool
	size += 1   // m.FullTunnel
	size += 2   // m.Mtu
	size += 2   // m.MssClamp
	size += 256 // m.DNSServers
	size += 512 // m.IncludeRoutes
	size += 512 // m.ExcludeRoutes
	return size
}
func (m *TlsctrlVPNProfileSet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Name, 64)
	buf.EncodeString(m.Pool, 64)
	buf.EncodeBool(m.FullTunnel)
	buf.EncodeUint16(m.Mtu)
	buf.EncodeUint16(m.MssClamp)
	buf.EncodeString(m.DNSServers, 256)
	buf.EncodeString(m.IncludeRoutes, 512)
	buf.EncodeString(m.ExcludeRoutes, 512)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNProfileSet) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Name = buf.DecodeString(64)
	m.Pool = buf.DecodeString(64)
	m.FullTunnel = buf.DecodeBool()
	m.Mtu = buf.DecodeUint16()
	m.MssClamp = buf.DecodeUint16()
	m.DNSServers = buf.DecodeString(256)
	m.IncludeRoutes = buf.DecodeString(512)
	m.ExcludeRoutes = buf.DecodeString(512)
	return nil
}

// TlsctrlVPNProfileSetReply defines message 'tlsctrl_vpn_profile_set_reply'.
type TlsctrlVPNProfileSetReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlVPNProfileSetReply) Reset()               { *m = TlsctrlVPNProfileSetReply{} }
func (*TlsctrlVPNProfileSetReply) GetMessageName() string { return "tlsctrl_vpn_profile_set_reply" }
func (*TlsctrlVPNProfileSetReply) GetCrcString() string   { return "e8d4e804" }
func (*TlsctrlVPNProfileSetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlVPNProfileSetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlVPNProfileSetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNProfileSetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// TlsctrlVPNProfileSetReplyReply defines message 'tlsctrl_vpn_profile_set_reply_reply'.
type TlsctrlVPNProfileSetReplyReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlVPNProfileSetReplyReply) Reset() { *m = TlsctrlVPNProfileSetReplyReply{} }
func (*TlsctrlVPNProfileSetReplyReply) GetMessageName() string {
	return "tlsctrl_vpn_profile_set_reply_reply"
}
func (*TlsctrlVPNProfileSetReplyReply) GetCrcString() string { return "e8d4e804" }
func (*TlsctrlVPNProfileSetReplyReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlVPNProfileSetReplyReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlVPNProfileSetReplyReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNProfileSetReplyReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// TlsctrlVPNTunnelClose defines message 'tlsctrl_vpn_tunnel_close'.
type TlsctrlVPNTunnelClose struct {
	Username string `binapi:"string[64],name=username" json:"username,omitempty"`
}

func (m *TlsctrlVPNTunnelClose) Reset()               { *m = TlsctrlVPNTunnelClose{} }
func (*TlsctrlVPNTunnelClose) GetMessageName() string { return "tlsctrl_vpn_tunnel_close" }
func (*TlsctrlVPNTunnelClose) GetCrcString() string   { return "9c89e81e" }
func (*TlsctrlVPNTunnelClose) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlVPNTunnelClose) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 64 // m.Username
	return size
}
func (m *TlsctrlVPNTunnelClose) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Username, 64)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNTunnelClose) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Username = buf.DecodeString(64)
	return nil
}

// TlsctrlVPNTunnelCloseReply defines message 'tlsctrl_vpn_tunnel_close_reply'.
type TlsctrlVPNTunnelCloseReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlVPNTunnelCloseReply) Reset()               { *m = TlsctrlVPNTunnelCloseReply{} }
func (*TlsctrlVPNTunnelCloseReply) GetMessageName() string { return "tlsctrl_vpn_tunnel_close_reply" }
func (*TlsctrlVPNTunnelCloseReply) GetCrcString() string   { return "e8d4e804" }
func (*TlsctrlVPNTunnelCloseReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlVPNTunnelCloseReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlVPNTunnelCloseReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNTunnelCloseReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// TlsctrlVPNTunnelCloseReplyReply defines message 'tlsctrl_vpn_tunnel_close_reply_reply'.
type TlsctrlVPNTunnelCloseReplyReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlVPNTunnelCloseReplyReply) Reset() { *m = TlsctrlVPNTunnelCloseReplyReply{} }
func (*TlsctrlVPNTunnelCloseReplyReply) GetMessageName() string {
	return "tlsctrl_vpn_tunnel_close_reply_reply"
}
func (*TlsctrlVPNTunnelCloseReplyReply) GetCrcString() string { return "e8d4e804" }
func (*TlsctrlVPNTunnelCloseReplyReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlVPNTunnelCloseReplyReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlVPNTunnelCloseReplyReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNTunnelCloseReplyReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// TlsctrlVPNTunnelDetails defines message 'tlsctrl_vpn_tunnel_details'.
type TlsctrlVPNTunnelDetails struct {
	TunnelID       uint32 `binapi:"u32,name=tunnel_id" json:"tunnel_id,omitempty"`
	Username       string `binapi:"string[64],name=username" json:"username,omitempty"`
	Profile        string `binapi:"string[64],name=profile" json:"profile,omitempty"`
	AssignedIP     string `binapi:"string[64],name=assigned_ip" json:"assigned_ip,omitempty"`
	ClientIP       string `binapi:"string[64],name=client_ip" json:"client_ip,omitempty"`
	Running        bool   `binapi:"bool,name=running" json:"running,omitempty"`
	LastSeenUnixNs uint64 `binapi:"u64,name=last_seen_unix_ns" json:"last_seen_unix_ns,omitempty"`
}

func (m *TlsctrlVPNTunnelDetails) Reset()               { *m = TlsctrlVPNTunnelDetails{} }
func (*TlsctrlVPNTunnelDetails) GetMessageName() string { return "tlsctrl_vpn_tunnel_details" }
func (*TlsctrlVPNTunnelDetails) GetCrcString() string   { return "4698cc35" }
func (*TlsctrlVPNTunnelDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlVPNTunnelDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4  // m.TunnelID
	size += 64 // m.Username
	size += 64 // m.Profile
	size += 64 // m.AssignedIP
	size += 64 // m.ClientIP
	size += 1  // m.Running
	size += 8  // m.LastSeenUnixNs
	return size
}
func (m *TlsctrlVPNTunnelDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint32(m.TunnelID)
	buf.EncodeString(m.Username, 64)
	buf.EncodeString(m.Profile, 64)
	buf.EncodeString(m.AssignedIP, 64)
	buf.EncodeString(m.ClientIP, 64)
	buf.EncodeBool(m.Running)
	buf.EncodeUint64(m.LastSeenUnixNs)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNTunnelDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.TunnelID = buf.DecodeUint32()
	m.Username = buf.DecodeString(64)
	m.Profile = buf.DecodeString(64)
	m.AssignedIP = buf.DecodeString(64)
	m.ClientIP = buf.DecodeString(64)
	m.Running = buf.DecodeBool()
	m.LastSeenUnixNs = buf.DecodeUint64()
	return nil
}

// TlsctrlVPNTunnelDump defines message 'tlsctrl_vpn_tunnel_dump'.
type TlsctrlVPNTunnelDump struct{}

func (m *TlsctrlVPNTunnelDump) Reset()               { *m = TlsctrlVPNTunnelDump{} }
func (*TlsctrlVPNTunnelDump) GetMessageName() string { return "tlsctrl_vpn_tunnel_dump" }
func (*TlsctrlVPNTunnelDump) GetCrcString() string   { return "51077d14" }
func (*TlsctrlVPNTunnelDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlVPNTunnelDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *TlsctrlVPNTunnelDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNTunnelDump) Unmarshal(b []byte) error {
	return nil
}

// TlsctrlVPNTunnelOpen defines message 'tlsctrl_vpn_tunnel_open'.
type TlsctrlVPNTunnelOpen struct {
	Username string `binapi:"string[64],name=username" json:"username,omitempty"`
	Profile  string `binapi:"string[64],name=profile" json:"profile,omitempty"`
	ClientIP string `binapi:"string[64],name=client_ip" json:"client_ip,omitempty"`
}

func (m *TlsctrlVPNTunnelOpen) Reset()               { *m = TlsctrlVPNTunnelOpen{} }
func (*TlsctrlVPNTunnelOpen) GetMessageName() string { return "tlsctrl_vpn_tunnel_open" }
func (*TlsctrlVPNTunnelOpen) GetCrcString() string   { return "b8407dd0" }
func (*TlsctrlVPNTunnelOpen) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlVPNTunnelOpen) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 64 // m.Username
	size += 64 // m.Profile
	size += 64 // m.ClientIP
	return size
}
func (m *TlsctrlVPNTunnelOpen) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Username, 64)
	buf.EncodeString(m.Profile, 64)
	buf.EncodeString(m.ClientIP, 64)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNTunnelOpen) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Username = buf.DecodeString(64)
	m.Profile = buf.DecodeString(64)
	m.ClientIP = buf.DecodeString(64)
	return nil
}

// TlsctrlVPNTunnelOpenReply defines message 'tlsctrl_vpn_tunnel_open_reply'.
type TlsctrlVPNTunnelOpenReply struct {
	Retval        int32  `binapi:"i32,name=retval" json:"retval,omitempty"`
	TunnelID      uint32 `binapi:"u32,name=tunnel_id" json:"tunnel_id,omitempty"`
	AssignedIP    string `binapi:"string[64],name=assigned_ip" json:"assigned_ip,omitempty"`
	Gateway       string `binapi:"string[64],name=gateway" json:"gateway,omitempty"`
	DNSServers    string `binapi:"string[256],name=dns_servers" json:"dns_servers,omitempty"`
	IncludeRoutes string `binapi:"string[512],name=include_routes" json:"include_routes,omitempty"`
	ExcludeRoutes string `binapi:"string[512],name=exclude_routes" json:"exclude_routes,omitempty"`
	FullTunnel    bool   `binapi:"bool,name=full_tunnel" json:"full_tunnel,omitempty"`
	Mtu           uint16 `binapi:"u16,name=mtu" json:"mtu,omitempty"`
	MssClamp      uint16 `binapi:"u16,name=mss_clamp" json:"mss_clamp,omitempty"`
	LeaseSeconds  uint32 `binapi:"u32,name=lease_seconds" json:"lease_seconds,omitempty"`
}

func (m *TlsctrlVPNTunnelOpenReply) Reset()               { *m = TlsctrlVPNTunnelOpenReply{} }
func (*TlsctrlVPNTunnelOpenReply) GetMessageName() string { return "tlsctrl_vpn_tunnel_open_reply" }
func (*TlsctrlVPNTunnelOpenReply) GetCrcString() string   { return "371038ba" }
func (*TlsctrlVPNTunnelOpenReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlVPNTunnelOpenReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4   // m.Retval
	size += 4   // m.TunnelID
	size += 64  // m.AssignedIP
	size += 64  // m.Gateway
	size += 256 // m.DNSServers
	size += 512 // m.IncludeRoutes
	size += 512 // m.ExcludeRoutes
	size += 1   // m.FullTunnel
	size += 2   // m.Mtu
	size += 2   // m.MssClamp
	size += 4   // m.LeaseSeconds
	return size
}
func (m *TlsctrlVPNTunnelOpenReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint32(m.TunnelID)
	buf.EncodeString(m.AssignedIP, 64)
	buf.EncodeString(m.Gateway, 64)
	buf.EncodeString(m.DNSServers, 256)
	buf.EncodeString(m.IncludeRoutes, 512)
	buf.EncodeString(m.ExcludeRoutes, 512)
	buf.EncodeBool(m.FullTunnel)
	buf.EncodeUint16(m.Mtu)
	buf.EncodeUint16(m.MssClamp)
	buf.EncodeUint32(m.LeaseSeconds)
	return buf.Bytes(), nil
}
func (m *TlsctrlVPNTunnelOpenReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.TunnelID = buf.DecodeUint32()
	m.AssignedIP = buf.DecodeString(64)
	m.Gateway = buf.DecodeString(64)
	m.DNSServers = buf.DecodeString(256)
	m.IncludeRoutes = buf.DecodeString(512)
	m.ExcludeRoutes = buf.DecodeString(512)
	m.FullTunnel = buf.DecodeBool()
	m.Mtu = buf.DecodeUint16()
	m.MssClamp = buf.DecodeUint16()
	m.LeaseSeconds = buf.DecodeUint32()
	return nil
}

func init() { file_tlsctrl_vpn_binapi_init() }
func file_tlsctrl_vpn_binapi_init() {
	api.RegisterMessage((*TlsctrlVPNConnectConfigGet)(nil), "tlsctrl_vpn_connect_config_get_b8407dd0")
	api.RegisterMessage((*TlsctrlVPNConnectConfigGetReply)(nil), "tlsctrl_vpn_connect_config_get_reply_371038ba")
	api.RegisterMessage((*TlsctrlVPNPoolDetails)(nil), "tlsctrl_vpn_pool_details_5d6d14af")
	api.RegisterMessage((*TlsctrlVPNPoolDump)(nil), "tlsctrl_vpn_pool_dump_51077d14")
	api.RegisterMessage((*TlsctrlVPNPoolSet)(nil), "tlsctrl_vpn_pool_set_da3bc5ef")
	api.RegisterMessage((*TlsctrlVPNPoolSetReply)(nil), "tlsctrl_vpn_pool_set_reply_e8d4e804")
	api.RegisterMessage((*TlsctrlVPNPoolSetReplyReply)(nil), "tlsctrl_vpn_pool_set_reply_reply_e8d4e804")
	api.RegisterMessage((*TlsctrlVPNProfileDetails)(nil), "tlsctrl_vpn_profile_details_fb19d1c0")
	api.RegisterMessage((*TlsctrlVPNProfileDump)(nil), "tlsctrl_vpn_profile_dump_51077d14")
	api.RegisterMessage((*TlsctrlVPNProfileSet)(nil), "tlsctrl_vpn_profile_set_27d2fd24")
	api.RegisterMessage((*TlsctrlVPNProfileSetReply)(nil), "tlsctrl_vpn_profile_set_reply_e8d4e804")
	api.RegisterMessage((*TlsctrlVPNProfileSetReplyReply)(nil), "tlsctrl_vpn_profile_set_reply_reply_e8d4e804")
	api.RegisterMessage((*TlsctrlVPNTunnelClose)(nil), "tlsctrl_vpn_tunnel_close_9c89e81e")
	api.RegisterMessage((*TlsctrlVPNTunnelCloseReply)(nil), "tlsctrl_vpn_tunnel_close_reply_e8d4e804")
	api.RegisterMessage((*TlsctrlVPNTunnelCloseReplyReply)(nil), "tlsctrl_vpn_tunnel_close_reply_reply_e8d4e804")
	api.RegisterMessage((*TlsctrlVPNTunnelDetails)(nil), "tlsctrl_vpn_tunnel_details_4698cc35")
	api.RegisterMessage((*TlsctrlVPNTunnelDump)(nil), "tlsctrl_vpn_tunnel_dump_51077d14")
	api.RegisterMessage((*TlsctrlVPNTunnelOpen)(nil), "tlsctrl_vpn_tunnel_open_b8407dd0")
	api.RegisterMessage((*TlsctrlVPNTunnelOpenReply)(nil), "tlsctrl_vpn_tunnel_open_reply_371038ba")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*TlsctrlVPNConnectConfigGet)(nil),
		(*TlsctrlVPNConnectConfigGetReply)(nil),
		(*TlsctrlVPNPoolDetails)(nil),
		(*TlsctrlVPNPoolDump)(nil),
		(*TlsctrlVPNPoolSet)(nil),
		(*TlsctrlVPNPoolSetReply)(nil),
		(*TlsctrlVPNPoolSetReplyReply)(nil),
		(*TlsctrlVPNProfileDetails)(nil),
		(*TlsctrlVPNProfileDump)(nil),
		(*TlsctrlVPNProfileSet)(nil),
		(*TlsctrlVPNProfileSetReply)(nil),
		(*TlsctrlVPNProfileSetReplyReply)(nil),
		(*TlsctrlVPNTunnelClose)(nil),
		(*TlsctrlVPNTunnelCloseReply)(nil),
		(*TlsctrlVPNTunnelCloseReplyReply)(nil),
		(*TlsctrlVPNTunnelDetails)(nil),
		(*TlsctrlVPNTunnelDump)(nil),
		(*TlsctrlVPNTunnelOpen)(nil),
		(*TlsctrlVPNTunnelOpenReply)(nil),
	}
}
