// Code generated by GoVPP's binapi-generator. DO NOT EDIT.
// versions:
//  binapi-generator: v0.13.0
//  VPP:              26.06-rc0~373-ge425dad65
// source: plugins/tlsctrl.api.json

// Package tlsctrl contains generated bindings for API file tlsctrl.api.
//
// Contents:
// - 22 messages
package tlsctrl

import (
	api "go.fd.io/govpp/api"
	codec "go.fd.io/govpp/codec"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the GoVPP api package it is being compiled against.
// A compilation error at this line likely means your copy of the
// GoVPP api package needs to be updated.
const _ = api.GoVppAPIPackageIsVersion2

const (
	APIFile    = "tlsctrl"
	APIVersion = "0.2.0"
	VersionCrc = 0xc0055b31
)

// TlsctrlClientAppsGet defines message 'tlsctrl_client_apps_get'.
type TlsctrlClientAppsGet struct {
	Username string `binapi:"string[128],name=username" json:"username,omitempty"`
}

func (m *TlsctrlClientAppsGet) Reset()               { *m = TlsctrlClientAppsGet{} }
func (*TlsctrlClientAppsGet) GetMessageName() string { return "tlsctrl_client_apps_get" }
func (*TlsctrlClientAppsGet) GetCrcString() string   { return "688dee0b" }
func (*TlsctrlClientAppsGet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlClientAppsGet) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 128 // m.Username
	return size
}
func (m *TlsctrlClientAppsGet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Username, 128)
	return buf.Bytes(), nil
}
func (m *TlsctrlClientAppsGet) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Username = buf.DecodeString(128)
	return nil
}

// TlsctrlClientAppsGetReply defines message 'tlsctrl_client_apps_get_reply'.
type TlsctrlClientAppsGetReply struct {
	Retval            int32  `binapi:"i32,name=retval" json:"retval,omitempty"`
	Count             uint32 `binapi:"u32,name=count" json:"count,omitempty"`
	GeneratedAtUnixNs uint64 `binapi:"u64,name=generated_at_unix_ns" json:"generated_at_unix_ns,omitempty"`
	Payload           string `binapi:"string[65535],name=payload" json:"payload,omitempty"`
}

func (m *TlsctrlClientAppsGetReply) Reset()               { *m = TlsctrlClientAppsGetReply{} }
func (*TlsctrlClientAppsGetReply) GetMessageName() string { return "tlsctrl_client_apps_get_reply" }
func (*TlsctrlClientAppsGetReply) GetCrcString() string   { return "2a643c08" }
func (*TlsctrlClientAppsGetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlClientAppsGetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4     // m.Retval
	size += 4     // m.Count
	size += 8     // m.GeneratedAtUnixNs
	size += 65535 // m.Payload
	return size
}
func (m *TlsctrlClientAppsGetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeUint32(m.Count)
	buf.EncodeUint64(m.GeneratedAtUnixNs)
	buf.EncodeString(m.Payload, 65535)
	return buf.Bytes(), nil
}
func (m *TlsctrlClientAppsGetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.Count = buf.DecodeUint32()
	m.GeneratedAtUnixNs = buf.DecodeUint64()
	m.Payload = buf.DecodeString(65535)
	return nil
}

// TlsctrlClientAppsSet defines message 'tlsctrl_client_apps_set'.
type TlsctrlClientAppsSet struct {
	Username string `binapi:"string[128],name=username" json:"username,omitempty"`
	Count    uint32 `binapi:"u32,name=count" json:"count,omitempty"`
	Payload  string `binapi:"string[65535],name=payload" json:"payload,omitempty"`
}

func (m *TlsctrlClientAppsSet) Reset()               { *m = TlsctrlClientAppsSet{} }
func (*TlsctrlClientAppsSet) GetMessageName() string { return "tlsctrl_client_apps_set" }
func (*TlsctrlClientAppsSet) GetCrcString() string   { return "b5652a43" }
func (*TlsctrlClientAppsSet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlClientAppsSet) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 128   // m.Username
	size += 4     // m.Count
	size += 65535 // m.Payload
	return size
}
func (m *TlsctrlClientAppsSet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Username, 128)
	buf.EncodeUint32(m.Count)
	buf.EncodeString(m.Payload, 65535)
	return buf.Bytes(), nil
}
func (m *TlsctrlClientAppsSet) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Username = buf.DecodeString(128)
	m.Count = buf.DecodeUint32()
	m.Payload = buf.DecodeString(65535)
	return nil
}

// TlsctrlClientAppsSetReply defines message 'tlsctrl_client_apps_set_reply'.
type TlsctrlClientAppsSetReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlClientAppsSetReply) Reset()               { *m = TlsctrlClientAppsSetReply{} }
func (*TlsctrlClientAppsSetReply) GetMessageName() string { return "tlsctrl_client_apps_set_reply" }
func (*TlsctrlClientAppsSetReply) GetCrcString() string   { return "e8d4e804" }
func (*TlsctrlClientAppsSetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlClientAppsSetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlClientAppsSetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlClientAppsSetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// TlsctrlClientCommandGet defines message 'tlsctrl_client_command_get'.
type TlsctrlClientCommandGet struct {
	Username string `binapi:"string[128],name=username" json:"username,omitempty"`
}

func (m *TlsctrlClientCommandGet) Reset()               { *m = TlsctrlClientCommandGet{} }
func (*TlsctrlClientCommandGet) GetMessageName() string { return "tlsctrl_client_command_get" }
func (*TlsctrlClientCommandGet) GetCrcString() string   { return "688dee0b" }
func (*TlsctrlClientCommandGet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlClientCommandGet) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 128 // m.Username
	return size
}
func (m *TlsctrlClientCommandGet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Username, 128)
	return buf.Bytes(), nil
}
func (m *TlsctrlClientCommandGet) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Username = buf.DecodeString(128)
	return nil
}

// TlsctrlClientCommandGetReply defines message 'tlsctrl_client_command_get_reply'.
type TlsctrlClientCommandGetReply struct {
	Retval      int32  `binapi:"i32,name=retval" json:"retval,omitempty"`
	CommandType string `binapi:"string[64],name=command_type" json:"command_type,omitempty"`
	Payload     string `binapi:"string[4096],name=payload" json:"payload,omitempty"`
}

func (m *TlsctrlClientCommandGetReply) Reset() { *m = TlsctrlClientCommandGetReply{} }
func (*TlsctrlClientCommandGetReply) GetMessageName() string {
	return "tlsctrl_client_command_get_reply"
}
func (*TlsctrlClientCommandGetReply) GetCrcString() string { return "861c362a" }
func (*TlsctrlClientCommandGetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlClientCommandGetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4    // m.Retval
	size += 64   // m.CommandType
	size += 4096 // m.Payload
	return size
}
func (m *TlsctrlClientCommandGetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	buf.EncodeString(m.CommandType, 64)
	buf.EncodeString(m.Payload, 4096)
	return buf.Bytes(), nil
}
func (m *TlsctrlClientCommandGetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	m.CommandType = buf.DecodeString(64)
	m.Payload = buf.DecodeString(4096)
	return nil
}

// TlsctrlClientCommandSet defines message 'tlsctrl_client_command_set'.
type TlsctrlClientCommandSet struct {
	Username    string `binapi:"string[128],name=username" json:"username,omitempty"`
	CommandType string `binapi:"string[64],name=command_type" json:"command_type,omitempty"`
	Payload     string `binapi:"string[4096],name=payload" json:"payload,omitempty"`
}

func (m *TlsctrlClientCommandSet) Reset()               { *m = TlsctrlClientCommandSet{} }
func (*TlsctrlClientCommandSet) GetMessageName() string { return "tlsctrl_client_command_set" }
func (*TlsctrlClientCommandSet) GetCrcString() string   { return "399fa03e" }
func (*TlsctrlClientCommandSet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlClientCommandSet) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 128  // m.Username
	size += 64   // m.CommandType
	size += 4096 // m.Payload
	return size
}
func (m *TlsctrlClientCommandSet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Username, 128)
	buf.EncodeString(m.CommandType, 64)
	buf.EncodeString(m.Payload, 4096)
	return buf.Bytes(), nil
}
func (m *TlsctrlClientCommandSet) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Username = buf.DecodeString(128)
	m.CommandType = buf.DecodeString(64)
	m.Payload = buf.DecodeString(4096)
	return nil
}

// TlsctrlClientCommandSetReply defines message 'tlsctrl_client_command_set_reply'.
type TlsctrlClientCommandSetReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlClientCommandSetReply) Reset() { *m = TlsctrlClientCommandSetReply{} }
func (*TlsctrlClientCommandSetReply) GetMessageName() string {
	return "tlsctrl_client_command_set_reply"
}
func (*TlsctrlClientCommandSetReply) GetCrcString() string { return "e8d4e804" }
func (*TlsctrlClientCommandSetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlClientCommandSetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlClientCommandSetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlClientCommandSetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// TlsctrlClientHeartbeat defines message 'tlsctrl_client_heartbeat'.
type TlsctrlClientHeartbeat struct {
	Username       string `binapi:"string[128],name=username" json:"username,omitempty"`
	CertSerial     string `binapi:"string[256],name=cert_serial" json:"cert_serial,omitempty"`
	SystemUser     string `binapi:"string[128],name=system_user" json:"system_user,omitempty"`
	OsName         string `binapi:"string[64],name=os_name" json:"os_name,omitempty"`
	OsVersion      string `binapi:"string[128],name=os_version" json:"os_version,omitempty"`
	SystemUptime   string `binapi:"string[128],name=system_uptime" json:"system_uptime,omitempty"`
	IP             string `binapi:"string[64],name=ip" json:"ip,omitempty"`
	Mac            string `binapi:"string[64],name=mac" json:"mac,omitempty"`
	Source         string `binapi:"string[64],name=source" json:"source,omitempty"`
	InterfacesJSON string `binapi:"string[8192],name=interfaces_json" json:"interfaces_json,omitempty"`
	ConnectIntent  string `binapi:"string[64],name=connect_intent" json:"connect_intent,omitempty"`
}

func (m *TlsctrlClientHeartbeat) Reset()               { *m = TlsctrlClientHeartbeat{} }
func (*TlsctrlClientHeartbeat) GetMessageName() string { return "tlsctrl_client_heartbeat" }
func (*TlsctrlClientHeartbeat) GetCrcString() string   { return "d1c9b4c4" }
func (*TlsctrlClientHeartbeat) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlClientHeartbeat) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 128  // m.Username
	size += 256  // m.CertSerial
	size += 128  // m.SystemUser
	size += 64   // m.OsName
	size += 128  // m.OsVersion
	size += 128  // m.SystemUptime
	size += 64   // m.IP
	size += 64   // m.Mac
	size += 64   // m.Source
	size += 8192 // m.InterfacesJSON
	size += 64   // m.ConnectIntent
	return size
}
func (m *TlsctrlClientHeartbeat) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Username, 128)
	buf.EncodeString(m.CertSerial, 256)
	buf.EncodeString(m.SystemUser, 128)
	buf.EncodeString(m.OsName, 64)
	buf.EncodeString(m.OsVersion, 128)
	buf.EncodeString(m.SystemUptime, 128)
	buf.EncodeString(m.IP, 64)
	buf.EncodeString(m.Mac, 64)
	buf.EncodeString(m.Source, 64)
	buf.EncodeString(m.InterfacesJSON, 8192)
	buf.EncodeString(m.ConnectIntent, 64)
	return buf.Bytes(), nil
}
func (m *TlsctrlClientHeartbeat) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Username = buf.DecodeString(128)
	m.CertSerial = buf.DecodeString(256)
	m.SystemUser = buf.DecodeString(128)
	m.OsName = buf.DecodeString(64)
	m.OsVersion = buf.DecodeString(128)
	m.SystemUptime = buf.DecodeString(128)
	m.IP = buf.DecodeString(64)
	m.Mac = buf.DecodeString(64)
	m.Source = buf.DecodeString(64)
	m.InterfacesJSON = buf.DecodeString(8192)
	m.ConnectIntent = buf.DecodeString(64)
	return nil
}

// TlsctrlClientHeartbeatReply defines message 'tlsctrl_client_heartbeat_reply'.
type TlsctrlClientHeartbeatReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlClientHeartbeatReply) Reset()               { *m = TlsctrlClientHeartbeatReply{} }
func (*TlsctrlClientHeartbeatReply) GetMessageName() string { return "tlsctrl_client_heartbeat_reply" }
func (*TlsctrlClientHeartbeatReply) GetCrcString() string   { return "e8d4e804" }
func (*TlsctrlClientHeartbeatReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlClientHeartbeatReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlClientHeartbeatReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlClientHeartbeatReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// TlsctrlListenerConfigSet defines message 'tlsctrl_listener_config_set'.
type TlsctrlListenerConfigSet struct {
	ListenAddr    string `binapi:"string[128],name=listen_addr" json:"listen_addr,omitempty"`
	ListenPort    uint16 `binapi:"u16,name=listen_port" json:"listen_port,omitempty"`
	ServerCertPem string `binapi:"string[16384],name=server_cert_pem" json:"server_cert_pem,omitempty"`
	ServerKeyPem  string `binapi:"string[16384],name=server_key_pem" json:"server_key_pem,omitempty"`
	CaCertPem     string `binapi:"string[16384],name=ca_cert_pem" json:"ca_cert_pem,omitempty"`
}

func (m *TlsctrlListenerConfigSet) Reset()               { *m = TlsctrlListenerConfigSet{} }
func (*TlsctrlListenerConfigSet) GetMessageName() string { return "tlsctrl_listener_config_set" }
func (*TlsctrlListenerConfigSet) GetCrcString() string   { return "6824ba0d" }
func (*TlsctrlListenerConfigSet) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlListenerConfigSet) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 128   // m.ListenAddr
	size += 2     // m.ListenPort
	size += 16384 // m.ServerCertPem
	size += 16384 // m.ServerKeyPem
	size += 16384 // m.CaCertPem
	return size
}
func (m *TlsctrlListenerConfigSet) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.ListenAddr, 128)
	buf.EncodeUint16(m.ListenPort)
	buf.EncodeString(m.ServerCertPem, 16384)
	buf.EncodeString(m.ServerKeyPem, 16384)
	buf.EncodeString(m.CaCertPem, 16384)
	return buf.Bytes(), nil
}
func (m *TlsctrlListenerConfigSet) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.ListenAddr = buf.DecodeString(128)
	m.ListenPort = buf.DecodeUint16()
	m.ServerCertPem = buf.DecodeString(16384)
	m.ServerKeyPem = buf.DecodeString(16384)
	m.CaCertPem = buf.DecodeString(16384)
	return nil
}

// TlsctrlListenerConfigSetReply defines message 'tlsctrl_listener_config_set_reply'.
type TlsctrlListenerConfigSetReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlListenerConfigSetReply) Reset() { *m = TlsctrlListenerConfigSetReply{} }
func (*TlsctrlListenerConfigSetReply) GetMessageName() string {
	return "tlsctrl_listener_config_set_reply"
}
func (*TlsctrlListenerConfigSetReply) GetCrcString() string { return "e8d4e804" }
func (*TlsctrlListenerConfigSetReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlListenerConfigSetReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlListenerConfigSetReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlListenerConfigSetReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// TlsctrlSessionDetails defines message 'tlsctrl_session_details'.
type TlsctrlSessionDetails struct {
	Username            string `binapi:"string[128],name=username" json:"username,omitempty"`
	CertSerial          string `binapi:"string[256],name=cert_serial" json:"cert_serial,omitempty"`
	SystemUser          string `binapi:"string[128],name=system_user" json:"system_user,omitempty"`
	OsName              string `binapi:"string[64],name=os_name" json:"os_name,omitempty"`
	OsVersion           string `binapi:"string[128],name=os_version" json:"os_version,omitempty"`
	SystemUptime        string `binapi:"string[128],name=system_uptime" json:"system_uptime,omitempty"`
	IP                  string `binapi:"string[64],name=ip" json:"ip,omitempty"`
	Mac                 string `binapi:"string[64],name=mac" json:"mac,omitempty"`
	Source              string `binapi:"string[64],name=source" json:"source,omitempty"`
	InterfacesJSON      string `binapi:"string[8192],name=interfaces_json" json:"interfaces_json,omitempty"`
	Status              uint8  `binapi:"u8,name=status" json:"status,omitempty"`
	ConnectedAtUnixNs   uint64 `binapi:"u64,name=connected_at_unix_ns" json:"connected_at_unix_ns,omitempty"`
	LastSeenUnixNs      uint64 `binapi:"u64,name=last_seen_unix_ns" json:"last_seen_unix_ns,omitempty"`
	AppsUpdatedAtUnixNs uint64 `binapi:"u64,name=apps_updated_at_unix_ns" json:"apps_updated_at_unix_ns,omitempty"`
	AppsCount           uint32 `binapi:"u32,name=apps_count" json:"apps_count,omitempty"`
}

func (m *TlsctrlSessionDetails) Reset()               { *m = TlsctrlSessionDetails{} }
func (*TlsctrlSessionDetails) GetMessageName() string { return "tlsctrl_session_details" }
func (*TlsctrlSessionDetails) GetCrcString() string   { return "53402d57" }
func (*TlsctrlSessionDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlSessionDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 128  // m.Username
	size += 256  // m.CertSerial
	size += 128  // m.SystemUser
	size += 64   // m.OsName
	size += 128  // m.OsVersion
	size += 128  // m.SystemUptime
	size += 64   // m.IP
	size += 64   // m.Mac
	size += 64   // m.Source
	size += 8192 // m.InterfacesJSON
	size += 1    // m.Status
	size += 8    // m.ConnectedAtUnixNs
	size += 8    // m.LastSeenUnixNs
	size += 8    // m.AppsUpdatedAtUnixNs
	size += 4    // m.AppsCount
	return size
}
func (m *TlsctrlSessionDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Username, 128)
	buf.EncodeString(m.CertSerial, 256)
	buf.EncodeString(m.SystemUser, 128)
	buf.EncodeString(m.OsName, 64)
	buf.EncodeString(m.OsVersion, 128)
	buf.EncodeString(m.SystemUptime, 128)
	buf.EncodeString(m.IP, 64)
	buf.EncodeString(m.Mac, 64)
	buf.EncodeString(m.Source, 64)
	buf.EncodeString(m.InterfacesJSON, 8192)
	buf.EncodeUint8(m.Status)
	buf.EncodeUint64(m.ConnectedAtUnixNs)
	buf.EncodeUint64(m.LastSeenUnixNs)
	buf.EncodeUint64(m.AppsUpdatedAtUnixNs)
	buf.EncodeUint32(m.AppsCount)
	return buf.Bytes(), nil
}
func (m *TlsctrlSessionDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Username = buf.DecodeString(128)
	m.CertSerial = buf.DecodeString(256)
	m.SystemUser = buf.DecodeString(128)
	m.OsName = buf.DecodeString(64)
	m.OsVersion = buf.DecodeString(128)
	m.SystemUptime = buf.DecodeString(128)
	m.IP = buf.DecodeString(64)
	m.Mac = buf.DecodeString(64)
	m.Source = buf.DecodeString(64)
	m.InterfacesJSON = buf.DecodeString(8192)
	m.Status = buf.DecodeUint8()
	m.ConnectedAtUnixNs = buf.DecodeUint64()
	m.LastSeenUnixNs = buf.DecodeUint64()
	m.AppsUpdatedAtUnixNs = buf.DecodeUint64()
	m.AppsCount = buf.DecodeUint32()
	return nil
}

// TlsctrlSessionDisconnect defines message 'tlsctrl_session_disconnect'.
type TlsctrlSessionDisconnect struct {
	Username string `binapi:"string[128],name=username" json:"username,omitempty"`
}

func (m *TlsctrlSessionDisconnect) Reset()               { *m = TlsctrlSessionDisconnect{} }
func (*TlsctrlSessionDisconnect) GetMessageName() string { return "tlsctrl_session_disconnect" }
func (*TlsctrlSessionDisconnect) GetCrcString() string   { return "688dee0b" }
func (*TlsctrlSessionDisconnect) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlSessionDisconnect) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 128 // m.Username
	return size
}
func (m *TlsctrlSessionDisconnect) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Username, 128)
	return buf.Bytes(), nil
}
func (m *TlsctrlSessionDisconnect) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Username = buf.DecodeString(128)
	return nil
}

// TlsctrlSessionDisconnectReply defines message 'tlsctrl_session_disconnect_reply'.
type TlsctrlSessionDisconnectReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlSessionDisconnectReply) Reset() { *m = TlsctrlSessionDisconnectReply{} }
func (*TlsctrlSessionDisconnectReply) GetMessageName() string {
	return "tlsctrl_session_disconnect_reply"
}
func (*TlsctrlSessionDisconnectReply) GetCrcString() string { return "e8d4e804" }
func (*TlsctrlSessionDisconnectReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlSessionDisconnectReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlSessionDisconnectReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlSessionDisconnectReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// TlsctrlSessionDump defines message 'tlsctrl_session_dump'.
type TlsctrlSessionDump struct{}

func (m *TlsctrlSessionDump) Reset()               { *m = TlsctrlSessionDump{} }
func (*TlsctrlSessionDump) GetMessageName() string { return "tlsctrl_session_dump" }
func (*TlsctrlSessionDump) GetCrcString() string   { return "51077d14" }
func (*TlsctrlSessionDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlSessionDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *TlsctrlSessionDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *TlsctrlSessionDump) Unmarshal(b []byte) error {
	return nil
}

// TlsctrlUserAddDel defines message 'tlsctrl_user_add_del'.
type TlsctrlUserAddDel struct {
	IsAdd      uint8  `binapi:"u8,name=is_add" json:"is_add,omitempty"`
	Enabled    uint8  `binapi:"u8,name=enabled" json:"enabled,omitempty"`
	Username   string `binapi:"string[128],name=username" json:"username,omitempty"`
	CertSerial string `binapi:"string[256],name=cert_serial" json:"cert_serial,omitempty"`
}

func (m *TlsctrlUserAddDel) Reset()               { *m = TlsctrlUserAddDel{} }
func (*TlsctrlUserAddDel) GetMessageName() string { return "tlsctrl_user_add_del" }
func (*TlsctrlUserAddDel) GetCrcString() string   { return "d41cbaea" }
func (*TlsctrlUserAddDel) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlUserAddDel) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 1   // m.IsAdd
	size += 1   // m.Enabled
	size += 128 // m.Username
	size += 256 // m.CertSerial
	return size
}
func (m *TlsctrlUserAddDel) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeUint8(m.IsAdd)
	buf.EncodeUint8(m.Enabled)
	buf.EncodeString(m.Username, 128)
	buf.EncodeString(m.CertSerial, 256)
	return buf.Bytes(), nil
}
func (m *TlsctrlUserAddDel) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.IsAdd = buf.DecodeUint8()
	m.Enabled = buf.DecodeUint8()
	m.Username = buf.DecodeString(128)
	m.CertSerial = buf.DecodeString(256)
	return nil
}

// TlsctrlUserAddDelReply defines message 'tlsctrl_user_add_del_reply'.
type TlsctrlUserAddDelReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlUserAddDelReply) Reset()               { *m = TlsctrlUserAddDelReply{} }
func (*TlsctrlUserAddDelReply) GetMessageName() string { return "tlsctrl_user_add_del_reply" }
func (*TlsctrlUserAddDelReply) GetCrcString() string   { return "e8d4e804" }
func (*TlsctrlUserAddDelReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlUserAddDelReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlUserAddDelReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlUserAddDelReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

// TlsctrlUserDetails defines message 'tlsctrl_user_details'.
type TlsctrlUserDetails struct {
	Username       string `binapi:"string[128],name=username" json:"username,omitempty"`
	CertSerial     string `binapi:"string[256],name=cert_serial" json:"cert_serial,omitempty"`
	Enabled        uint8  `binapi:"u8,name=enabled" json:"enabled,omitempty"`
	Generation     uint64 `binapi:"u64,name=generation" json:"generation,omitempty"`
	LastSeenUnixNs uint64 `binapi:"u64,name=last_seen_unix_ns" json:"last_seen_unix_ns,omitempty"`
}

func (m *TlsctrlUserDetails) Reset()               { *m = TlsctrlUserDetails{} }
func (*TlsctrlUserDetails) GetMessageName() string { return "tlsctrl_user_details" }
func (*TlsctrlUserDetails) GetCrcString() string   { return "653d0b7c" }
func (*TlsctrlUserDetails) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlUserDetails) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 128 // m.Username
	size += 256 // m.CertSerial
	size += 1   // m.Enabled
	size += 8   // m.Generation
	size += 8   // m.LastSeenUnixNs
	return size
}
func (m *TlsctrlUserDetails) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Username, 128)
	buf.EncodeString(m.CertSerial, 256)
	buf.EncodeUint8(m.Enabled)
	buf.EncodeUint64(m.Generation)
	buf.EncodeUint64(m.LastSeenUnixNs)
	return buf.Bytes(), nil
}
func (m *TlsctrlUserDetails) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Username = buf.DecodeString(128)
	m.CertSerial = buf.DecodeString(256)
	m.Enabled = buf.DecodeUint8()
	m.Generation = buf.DecodeUint64()
	m.LastSeenUnixNs = buf.DecodeUint64()
	return nil
}

// TlsctrlUserDump defines message 'tlsctrl_user_dump'.
type TlsctrlUserDump struct{}

func (m *TlsctrlUserDump) Reset()               { *m = TlsctrlUserDump{} }
func (*TlsctrlUserDump) GetMessageName() string { return "tlsctrl_user_dump" }
func (*TlsctrlUserDump) GetCrcString() string   { return "51077d14" }
func (*TlsctrlUserDump) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlUserDump) Size() (size int) {
	if m == nil {
		return 0
	}
	return size
}
func (m *TlsctrlUserDump) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	return buf.Bytes(), nil
}
func (m *TlsctrlUserDump) Unmarshal(b []byte) error {
	return nil
}

// TlsctrlUserReissue defines message 'tlsctrl_user_reissue'.
type TlsctrlUserReissue struct {
	Username   string `binapi:"string[128],name=username" json:"username,omitempty"`
	CertSerial string `binapi:"string[256],name=cert_serial" json:"cert_serial,omitempty"`
}

func (m *TlsctrlUserReissue) Reset()               { *m = TlsctrlUserReissue{} }
func (*TlsctrlUserReissue) GetMessageName() string { return "tlsctrl_user_reissue" }
func (*TlsctrlUserReissue) GetCrcString() string   { return "e52efa23" }
func (*TlsctrlUserReissue) GetMessageType() api.MessageType {
	return api.RequestMessage
}

func (m *TlsctrlUserReissue) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 128 // m.Username
	size += 256 // m.CertSerial
	return size
}
func (m *TlsctrlUserReissue) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeString(m.Username, 128)
	buf.EncodeString(m.CertSerial, 256)
	return buf.Bytes(), nil
}
func (m *TlsctrlUserReissue) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Username = buf.DecodeString(128)
	m.CertSerial = buf.DecodeString(256)
	return nil
}

// TlsctrlUserReissueReply defines message 'tlsctrl_user_reissue_reply'.
type TlsctrlUserReissueReply struct {
	Retval int32 `binapi:"i32,name=retval" json:"retval,omitempty"`
}

func (m *TlsctrlUserReissueReply) Reset()               { *m = TlsctrlUserReissueReply{} }
func (*TlsctrlUserReissueReply) GetMessageName() string { return "tlsctrl_user_reissue_reply" }
func (*TlsctrlUserReissueReply) GetCrcString() string   { return "e8d4e804" }
func (*TlsctrlUserReissueReply) GetMessageType() api.MessageType {
	return api.ReplyMessage
}

func (m *TlsctrlUserReissueReply) Size() (size int) {
	if m == nil {
		return 0
	}
	size += 4 // m.Retval
	return size
}
func (m *TlsctrlUserReissueReply) Marshal(b []byte) ([]byte, error) {
	if b == nil {
		b = make([]byte, m.Size())
	}
	buf := codec.NewBuffer(b)
	buf.EncodeInt32(m.Retval)
	return buf.Bytes(), nil
}
func (m *TlsctrlUserReissueReply) Unmarshal(b []byte) error {
	buf := codec.NewBuffer(b)
	m.Retval = buf.DecodeInt32()
	return nil
}

func init() { file_tlsctrl_binapi_init() }
func file_tlsctrl_binapi_init() {
	api.RegisterMessage((*TlsctrlClientAppsGet)(nil), "tlsctrl_client_apps_get_688dee0b")
	api.RegisterMessage((*TlsctrlClientAppsGetReply)(nil), "tlsctrl_client_apps_get_reply_2a643c08")
	api.RegisterMessage((*TlsctrlClientAppsSet)(nil), "tlsctrl_client_apps_set_b5652a43")
	api.RegisterMessage((*TlsctrlClientAppsSetReply)(nil), "tlsctrl_client_apps_set_reply_e8d4e804")
	api.RegisterMessage((*TlsctrlClientCommandGet)(nil), "tlsctrl_client_command_get_688dee0b")
	api.RegisterMessage((*TlsctrlClientCommandGetReply)(nil), "tlsctrl_client_command_get_reply_861c362a")
	api.RegisterMessage((*TlsctrlClientCommandSet)(nil), "tlsctrl_client_command_set_399fa03e")
	api.RegisterMessage((*TlsctrlClientCommandSetReply)(nil), "tlsctrl_client_command_set_reply_e8d4e804")
	api.RegisterMessage((*TlsctrlClientHeartbeat)(nil), "tlsctrl_client_heartbeat_d1c9b4c4")
	api.RegisterMessage((*TlsctrlClientHeartbeatReply)(nil), "tlsctrl_client_heartbeat_reply_e8d4e804")
	api.RegisterMessage((*TlsctrlListenerConfigSet)(nil), "tlsctrl_listener_config_set_6824ba0d")
	api.RegisterMessage((*TlsctrlListenerConfigSetReply)(nil), "tlsctrl_listener_config_set_reply_e8d4e804")
	api.RegisterMessage((*TlsctrlSessionDetails)(nil), "tlsctrl_session_details_53402d57")
	api.RegisterMessage((*TlsctrlSessionDisconnect)(nil), "tlsctrl_session_disconnect_688dee0b")
	api.RegisterMessage((*TlsctrlSessionDisconnectReply)(nil), "tlsctrl_session_disconnect_reply_e8d4e804")
	api.RegisterMessage((*TlsctrlSessionDump)(nil), "tlsctrl_session_dump_51077d14")
	api.RegisterMessage((*TlsctrlUserAddDel)(nil), "tlsctrl_user_add_del_d41cbaea")
	api.RegisterMessage((*TlsctrlUserAddDelReply)(nil), "tlsctrl_user_add_del_reply_e8d4e804")
	api.RegisterMessage((*TlsctrlUserDetails)(nil), "tlsctrl_user_details_653d0b7c")
	api.RegisterMessage((*TlsctrlUserDump)(nil), "tlsctrl_user_dump_51077d14")
	api.RegisterMessage((*TlsctrlUserReissue)(nil), "tlsctrl_user_reissue_e52efa23")
	api.RegisterMessage((*TlsctrlUserReissueReply)(nil), "tlsctrl_user_reissue_reply_e8d4e804")
}

// Messages returns list of all messages in this module.
func AllMessages() []api.Message {
	return []api.Message{
		(*TlsctrlClientAppsGet)(nil),
		(*TlsctrlClientAppsGetReply)(nil),
		(*TlsctrlClientAppsSet)(nil),
		(*TlsctrlClientAppsSetReply)(nil),
		(*TlsctrlClientCommandGet)(nil),
		(*TlsctrlClientCommandGetReply)(nil),
		(*TlsctrlClientCommandSet)(nil),
		(*TlsctrlClientCommandSetReply)(nil),
		(*TlsctrlClientHeartbeat)(nil),
		(*TlsctrlClientHeartbeatReply)(nil),
		(*TlsctrlListenerConfigSet)(nil),
		(*TlsctrlListenerConfigSetReply)(nil),
		(*TlsctrlSessionDetails)(nil),
		(*TlsctrlSessionDisconnect)(nil),
		(*TlsctrlSessionDisconnectReply)(nil),
		(*TlsctrlSessionDump)(nil),
		(*TlsctrlUserAddDel)(nil),
		(*TlsctrlUserAddDelReply)(nil),
		(*TlsctrlUserDetails)(nil),
		(*TlsctrlUserDump)(nil),
		(*TlsctrlUserReissue)(nil),
		(*TlsctrlUserReissueReply)(nil),
	}
}
