// Code generated by GoVPP's binapi-generator. DO NOT EDIT.

package tlsctrl

import (
	"context"
	"fmt"
	"io"

	memclnt "github.com/srmkv/tlsctrl-agent/internal/vppbinapi/memclnt"
	api "go.fd.io/govpp/api"
)

// RPCService defines RPC service tlsctrl.
type RPCService interface {
	TlsctrlClientAppsGet(ctx context.Context, in *TlsctrlClientAppsGet) (*TlsctrlClientAppsGetReply, error)
	TlsctrlClientAppsSet(ctx context.Context, in *TlsctrlClientAppsSet) (*TlsctrlClientAppsSetReply, error)
	TlsctrlClientCommandGet(ctx context.Context, in *TlsctrlClientCommandGet) (*TlsctrlClientCommandGetReply, error)
	TlsctrlClientCommandSet(ctx context.Context, in *TlsctrlClientCommandSet) (*TlsctrlClientCommandSetReply, error)
	TlsctrlClientHeartbeat(ctx context.Context, in *TlsctrlClientHeartbeat) (*TlsctrlClientHeartbeatReply, error)
	TlsctrlListenerConfigSet(ctx context.Context, in *TlsctrlListenerConfigSet) (*TlsctrlListenerConfigSetReply, error)
	TlsctrlSessionDisconnect(ctx context.Context, in *TlsctrlSessionDisconnect) (*TlsctrlSessionDisconnectReply, error)
	TlsctrlSessionDump(ctx context.Context, in *TlsctrlSessionDump) (RPCService_TlsctrlSessionDumpClient, error)
	TlsctrlUserAddDel(ctx context.Context, in *TlsctrlUserAddDel) (*TlsctrlUserAddDelReply, error)
	TlsctrlUserDump(ctx context.Context, in *TlsctrlUserDump) (RPCService_TlsctrlUserDumpClient, error)
	TlsctrlUserReissue(ctx context.Context, in *TlsctrlUserReissue) (*TlsctrlUserReissueReply, error)
}

type serviceClient struct {
	conn api.Connection
}

func NewServiceClient(conn api.Connection) RPCService {
	return &serviceClient{conn}
}

func (c *serviceClient) TlsctrlClientAppsGet(ctx context.Context, in *TlsctrlClientAppsGet) (*TlsctrlClientAppsGetReply, error) {
	out := new(TlsctrlClientAppsGetReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) TlsctrlClientAppsSet(ctx context.Context, in *TlsctrlClientAppsSet) (*TlsctrlClientAppsSetReply, error) {
	out := new(TlsctrlClientAppsSetReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) TlsctrlClientCommandGet(ctx context.Context, in *TlsctrlClientCommandGet) (*TlsctrlClientCommandGetReply, error) {
	out := new(TlsctrlClientCommandGetReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) TlsctrlClientCommandSet(ctx context.Context, in *TlsctrlClientCommandSet) (*TlsctrlClientCommandSetReply, error) {
	out := new(TlsctrlClientCommandSetReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) TlsctrlClientHeartbeat(ctx context.Context, in *TlsctrlClientHeartbeat) (*TlsctrlClientHeartbeatReply, error) {
	out := new(TlsctrlClientHeartbeatReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) TlsctrlListenerConfigSet(ctx context.Context, in *TlsctrlListenerConfigSet) (*TlsctrlListenerConfigSetReply, error) {
	out := new(TlsctrlListenerConfigSetReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) TlsctrlSessionDisconnect(ctx context.Context, in *TlsctrlSessionDisconnect) (*TlsctrlSessionDisconnectReply, error) {
	out := new(TlsctrlSessionDisconnectReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) TlsctrlSessionDump(ctx context.Context, in *TlsctrlSessionDump) (RPCService_TlsctrlSessionDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_TlsctrlSessionDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_TlsctrlSessionDumpClient interface {
	Recv() (*TlsctrlSessionDetails, error)
	api.Stream
}

type serviceClient_TlsctrlSessionDumpClient struct {
	api.Stream
}

func (c *serviceClient_TlsctrlSessionDumpClient) Recv() (*TlsctrlSessionDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *TlsctrlSessionDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) TlsctrlUserAddDel(ctx context.Context, in *TlsctrlUserAddDel) (*TlsctrlUserAddDelReply, error) {
	out := new(TlsctrlUserAddDelReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}

func (c *serviceClient) TlsctrlUserDump(ctx context.Context, in *TlsctrlUserDump) (RPCService_TlsctrlUserDumpClient, error) {
	stream, err := c.conn.NewStream(ctx)
	if err != nil {
		return nil, err
	}
	x := &serviceClient_TlsctrlUserDumpClient{stream}
	if err := x.Stream.SendMsg(in); err != nil {
		return nil, err
	}
	if err = x.Stream.SendMsg(&memclnt.ControlPing{}); err != nil {
		return nil, err
	}
	return x, nil
}

type RPCService_TlsctrlUserDumpClient interface {
	Recv() (*TlsctrlUserDetails, error)
	api.Stream
}

type serviceClient_TlsctrlUserDumpClient struct {
	api.Stream
}

func (c *serviceClient_TlsctrlUserDumpClient) Recv() (*TlsctrlUserDetails, error) {
	msg, err := c.Stream.RecvMsg()
	if err != nil {
		return nil, err
	}
	switch m := msg.(type) {
	case *TlsctrlUserDetails:
		return m, nil
	case *memclnt.ControlPingReply:
		err = c.Stream.Close()
		if err != nil {
			return nil, err
		}
		return nil, io.EOF
	default:
		return nil, fmt.Errorf("unexpected message: %T %v", m, m)
	}
}

func (c *serviceClient) TlsctrlUserReissue(ctx context.Context, in *TlsctrlUserReissue) (*TlsctrlUserReissueReply, error) {
	out := new(TlsctrlUserReissueReply)
	err := c.conn.Invoke(ctx, in, out)
	if err != nil {
		return nil, err
	}
	return out, api.RetvalToVPPApiError(out.Retval)
}
